spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
  config:
    import:
    - optional:configserver:http://localhost:8888
    - classpath:secrets.yml
  application:
    name: user-service
server:
  port: 8080

secrets:
  jwtSecret: ${JWT_SECRET}
  accessTokenExpiration: ${JWT_ACCESS_EXPIRATION}
  refreshTokenExpiration: ${JWT_REFRESH_EXPIRATION}
  refreshCookieExpiration: ${COOKIE_REFRESH_EXPIRATION}
