spring:
  application:
    name: product-service
  datasource:
    password: root
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/products
    username: ann
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

  flyway:
    baseline-on-migrate: true
    password: root
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/products
    enabled: true
    user: ann
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}



server:
  port: 8050