spring:
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  kafka:
    consumer:
      group-id: notification-id
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  mail:
    host: smtp.gmail.com
    port: 587
    username: lvivcroissaintspet@gmail.com
    password: hser xfeb dgdb anrz
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
  application:
    name: notification-service
server:
  port: 8040
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
