

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:

  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
server:
  port: 8888
